/*
 * generated by Xtext
 */
package org.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LuaUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.ui.internal.LuaActivator.getInstance().getInjector("org.xtext.Lua");
	}
	
}
